config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
	get 'families/reports', as: 'report'
	get 'families/:family_id/kids',to: 'families#kids', as: 'family_kids'
	resources :families do
	resources :members
	end
	root 'welcome#index'
	

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/family.rb
class Family < ApplicationRecord

	has_many :members
	validates :name, presence: true,
                    length: { minimum: 5 }

	def self.get_families_with_kids
    Family.joins(:members).distinct
	end
 
  def get_kids
    members.where("age <= 10")
  end
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :family
 validates :name, presence: true,
                    length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController

	def index
	@families = Family.all
	end

	def show
	@family = Family.find(params[:id])
	end

	def new
	@family = Family.new
	end

	def edit
	@family = Family.find(params[:id])
	end
	
	def create
		@family = Family.new(family_params)

		if @family.save
			redirect_to @family
		else
			render 'new'
		end
	end

	def update
		@family = Family.find(params[:id])

		if @family.update(family_params)
			redirect_to @family
		else
			render 'edit'
		end
	end
	
	def destroy
		@family = Family.find(params[:id])
		@family.destroy
	 
		redirect_to families_path
	end

	def reports
		@families = Family.get_families_with_kids
	end

  def kids
    family = Family.find(params[:family_id])
    @members = family.get_kids
  end
 
	private
		def family_params
		  params.require(:family).permit(:name, :address)
		end	
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
   def create
    @family = Family.find(params[:family_id])
    puts "#"*10
    puts member_params.inspect
    puts "#"*10
    @member = @family.members.create(member_params)
    redirect_to family_path(@family)
  end

	def destroy
    @family = Family.find(params[:family_id])
    @member = @family.members.find(params[:id])
    @member.destroy
    redirect_to family_path(@family)
  end
 
  private
    def member_params
      params.require(:member).permit(:name, :age, :gender)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/f_helper.rb
module FHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/families/_form.html.erb
<%= form_for @family do |f| %>

		<% if @family.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@family.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @family.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/families/edit.html.erb
<h2>Edit Family</h2>

<%= render 'form' %>
 
<%= link_to 'Back', families_path %>

app/views/families/index.html.erb
<h1>Listing families</h1>

	<table>
<links>
<%= link_to 'New Family',new_family_path %><br>
<%= link_to 'Reports', report_path %>
</links>
<p id = "p01">	
	<tr>
	<th>Name</th>
	<th>Surname</th>
	<th colspan="3"></th>
	</tr>
</p>
	<% @families.each do |family| %>
<p id = "p02">	
	<tr>
	<td><%= family.name %></td>
	<td><%= family.address %></td>
	<td><%= link_to 'Show', family_path(family) %></td>
	<td><%= link_to 'Edit', edit_family_path(family) %></td>
	<td><%= link_to 'Destroy', family_path(family),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
	</tr>
</p>
	<% end %>
	</table>

app/views/families/kids.html.erb
<% @members.each do |member| %>
  <p>
    <strong>Name:</strong>
    <%= member.name %>
  </p>
 
  <p>
    <strong>Age:</strong>
    <%= member.age %>
  </p>
	<strong>Gender:</strong>
	<%= member.gender ? 'male' : 'female' %>
  
	<p>
	</p>
<% end %>

app/views/families/new.html.erb
<h2>New Family</h2>

<%= render 'form' %>
 
<%= link_to 'Back', families_path %>

app/views/families/reports.html.erb
<h> List of Families with kids </h>
<table>

	<tr>
	<th>Name</th>
	<th>Address</th>
        <th>Kids count</th>
	<th colspan="3"></th>
	</tr>

<% @families.each do |f| %>
<tr>
<td><%= f.name %></td>
<td><%= f.address %></td>
<td><%= link_to "kids", family_kids_path(f) %></td>
</tr>
<%end%>
</table>

app/views/families/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @family.name %>
</p>
 
<p>
  <strong>Address:</strong>
  <%= @family.address %>
</p>
<h2>Members:</h2>
<% @family.members.each do |member| %>
  <p>
    <strong>Name:</strong>
    <%= member.name %>
  </p>
 
  <p>
    <strong>Age:</strong>
    <%= member.age %>
  </p>
	<strong>Gender:</strong>
	<%= member.gender ? 'male' : 'female' %>
  
	<p>
	</p>

<%= link_to 'Destroy Member', [member.family, member],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
<% end %>
	<h2>Add a member:</h2>
<%= form_for([@family, @family.members.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </p>
	<p>
    <b>Gender:</b><br />
    <div class="form-group">
  
   <%= f.radio_button :gender, true %>
	 <%= f.label :gender_male, 'male' %><br />
   <%= f.radio_button :gender, false %>
	<%= f.label :gender_female, 'female' %>
</div>
</p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Edit',edit_family_path(@family) %>
<%= link_to 'Back', families_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Village</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcomeindex</h1>

<%= link_to 'My Blog', controller: 'families' %>